resolver: lts-8.3

packages:
- '.'
- location:
    git:    https://github.com/abakst/Brisk
    commit: 41102d5f6a81e22c0537eeeecbda54bf13d6e2f1
  extra-dep: true
- location:
    git:    https://github.com/abakst/brisk-prelude
    commit: 0f6eecd56c6dc1a57cdc80cf86f56ee1e5b262af
  extra-dep: true
extra-deps:
- distributed-process-async-0.2.3
- distributed-process-extras-0.2.1.2
- distributed-process-client-server-0.1.3.2

flags: {}

extra-package-dbs: []

