resolver: lts-8.3

packages:
- '.'
- location:
    git:    https://github.com/abakst/Brisk
    commit: e32d0694a643842d111f148bb2f8dae555e9fc15
  extra-dep: true
- location:
    git:    https://github.com/abakst/brisk-prelude
    commit: 8384991a88bd8f87f4002c88082f916c6dff3cfb
  extra-dep: true
extra-deps:
- distributed-process-0.6.6
- distributed-process-async-0.2.3
- distributed-process-extras-0.2.1.2
- distributed-process-client-server-0.1.3.2

flags: {}

extra-package-dbs: []

